remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

title: An ESports Earnings Data App by Ziyi Zhao and Cheng Ma
description: An Interactive Data App 

show_downloads: ["true"]
