remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Ziyi Zhao and Cheng Ma
description: our personal website

show_downloads: ["true"]
